thebetjr:
  twitter_user: 'thebet'
  twitter_pass: 'y4nk33s'
  base_url: 'http://thebetjr.gunnerweb.net'

thebet:
  twitter_user: 'thebet'
  twitter_pass: 'y4nk33s'
  base_url: 'http://thebet.gunnerweb.net'
